### ISSUE TITLE
Exchanges with Invalid Image Uri "{missing_small.png}"

### ISSUE THREAD

**Issue by GonzoKK** [tosunthex/CoinGecko#1]
Hi Thanks for this library! Its working very well.

Currently two exchanges CBX and VinEX have invalid Image uris and subsequently I get downstream exceptions "This operation is not supported for a relative URI". I'd prefer not to have to check each exchange (parse for IsAbsoluteUri) and then workaround. 

Any thoughts on perhaps addressing at class level? eg changing Image from Uri to string 

![image](https://user-images.githubusercontent.com/38913162/52852152-7c8f6e80-3120-11e9-8f19-7848b5bab223.png)

**Comment by tosunthex** [comment]
Hi @GonzoKK 

Thanks for your Issue. I Checked CBX and VinEx but i didn't see any problem maybe Coin Gecko fixed the image problem. But I found another problem and fixed that. If you see any problem or error please inform me.

![screenshot from 2019-02-15 21-15-38](https://user-images.githubusercontent.com/2063672/52897488-73aca480-31d5-11e9-845e-72d19d1fd3d2.png)
![screenshot from 2019-02-15 21-21-39](https://user-images.githubusercontent.com/2063672/52897490-75766800-31d5-11e9-9f1c-48149db22121.png)

**Comment by GonzoKK** [comment]
Hi @tosunthex  Yes CoinGecko fixed it.

I'm still flagging for Exchanges that could fail `IsAbsoluteUri` as my batch serialisation to LitEDB currently creates an exception if i include them.  

`var listBADExchanges = listExchanges.Where(x => !x.Url.IsAbsoluteUri || !x.Image.IsAbsoluteUri).ToList();`
  
![image](https://user-images.githubusercontent.com/38913162/52898076-2b47b380-31e2-11e9-81e7-79dd9ae8fb73.png)

**Comment by tosunthex** [comment]
hi @GonzoKK 

I added Exchanges_Images_Url_Count_Must_Equal_Total_Count test to ExchangesClientTest file and i cant catch this error.

**Comment by GonzoKK** [comment]
This error will only occur if/when CoinGecko add an exchange without an image for the exchange. Not sure how often this occurs...

**Comment by tosunthex** [comment]
Hi @GonzoKK I changed the Uri type to string it fixed the problem
