### ISSUE TITLE
CoinMarkets missing "sparkline_in_7d" property

### ISSUE THREAD

**Issue by GonzoKK** [tosunthex/CoinGecko#10]
[JsonProperty("sparkline_in_7d")]
public SparklineIn7D SparklineIn7D { get; set; }

https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=beam&order=market_cap_desc&per_page=100&page=1&sparkline=true

**Comment by tosunthex** [comment]
hi @GonzoKK 

Sparkline added to GetCoinMarkets and GetAllCoinDataWithId methods thx for support my repository. I can't see you mail address to contact with you.  If you are working on open source projects I want to help you. Please contact with me.
