### ISSUE TITLE
trade_url / TradeUrl property is missing in CoinGecko.Entities.Response.Shared.Ticker

### ISSUE THREAD

**Issue by jpaarhuis** [tosunthex/CoinGecko#11]
I'm missing the trade_url property that is available in the public HTTP API. Could you add this property?

Thanks

**Comment by tosunthex** [comment]
Hi @tosunthex 

I think trade_url property that you need is in this end point. 

`https://api.coingecko.com/api/v3/coins/bitcoin`

You can find the property under Ticker class

**Comment by jpaarhuis** [comment]
I saw you just added it in the last commit. Thanks!
