### ISSUE TITLE
problem when converting "reddit_accounts_active_48h"

### ISSUE THREAD

**Issue by Alexeix** [tosunthex/CoinGecko#12]
There was a problem when I executed method:
`_client.CoinsClient.GetHistoryByCoinId(CoinIds.First().Value, "01-12-2018", "false");`
I got the answer contains this:

```
...
"community_data":{"facebook_likes":1223,
"twitter_followers":null,
"reddit_average_posts_48h":0.0,
"reddit_average_comments_48h":0.0,
"reddit_subscribers":132,
"reddit_accounts_active_48h":"12.2916666666667"},
"developer_data":{"forks":null,"stars":null,"subscribers":null,"total_issues":null,"closed_issues":null,"pull_requests_merged":null,"pull_request_contributors":null,"commit_count_4_weeks":null},
"public_interest_stats":{"alexa_rank":2548131,"bing_matches":186000}}
```
In the class property expects: long, 

> [JsonProperty("reddit_accounts_active_48h")]
>         public long? RedditAccountsActive48H { get; set; }

to fix that we must change it to:

**public decimal? RedditAccountsActive48H { get; set; }**

**"reddit_accounts_active_48h":"12.2916666666667"**

**Comment by tosunthex** [comment]
Hi @Alexeix 

This number is too strange. Could you tell me the coin Id please ?

**Comment by tosunthex** [comment]
hi @Alexeix 

Thanks for your issue. I fixed the problem.
