### ISSUE TITLE
block_time_in_minutes / BlockTimeInMinutes missing in CoinByIdFullData

### ISSUE THREAD

**Issue by jpaarhuis** [tosunthex/CoinGecko#13]
The property block_time_in_minutes which is available in the REST API isn't available in the .NET client. Can we get that property as well in CoinByIdFullData?

Thanks

**Comment by jpaarhuis** [comment]
Any update on this?

**Comment by tosunthex** [comment]
Hi  @jpaarhuis 

Sorry for late answer I just push the new version.

**Comment by jpaarhuis** [comment]
Thanks man for making this happen again!
