### ISSUE TITLE
Which .Net version am I supposed to target?

### ISSUE THREAD

**Issue by element2** [tosunthex/CoinGecko#16]
Which .Net am I supposed to be targeting? Whether I choose .Net 2, 3 or 4.5 for my project and try to import it via Nuget, I get this: "Could not install package 'CoinGeckoAsyncApi 1.2.6'. You are trying to install this package into a project that targets '.NETFramework,Version=v3.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author"

![000259](https://user-images.githubusercontent.com/5205381/81970108-d9076500-95d3-11ea-87ce-2d818a4914cd.png)

**Comment by tosunthex** [comment]
hi @element2 sorry my late answer but you need to use .net core for using this package.
