### ISSUE TITLE
Market Cap Null hits error. (Example Coin : Statera)

### ISSUE THREAD

**Issue by nitezshiro** [tosunthex/CoinGecko#17]
MarketOhlcv.cs Line 9

[JsonProperty("market_cap_rank")]
public long MarketCapRank { get; set; }

It should be 
[JsonProperty("market_cap_rank")]
public long**?** MarketCapRank { get; set; }

missing ? to handle null value.

**Comment by jpaarhuis** [comment]
Please fix this, I'm having the same. Thanks.

**Comment by tosunthex** [comment]
@jpaarhuis @nitezshiro fixed
