### ISSUE TITLE
Ticker.cs The type or namespace name 'Market' could not be found

### ISSUE THREAD

**Issue by GonzoKK** [tosunthex/CoinGecko#2]
Fixed by adding `using CoinGecko.Entities.Response.Exchanges;`

![image](https://user-images.githubusercontent.com/38913162/52898382-c1310d80-31e5-11e9-8969-2ce0a2e05111.png)

**Comment by tosunthex** [comment]
Hi @GonzoKK 

Market.cs files must be inside of the Shared folder so you don't need to add using for that. For file you can check the reposity. But thanks for the issue Market.cs file inside of the Exchanges directory is dublicated file and i will delete that.

[https://github.com/tosunthex/CoinGecko/blob/master/CoinGecko/Entities/Response/Shared/Market.cs](url)
