### ISSUE TITLE
Doubles Vs Decimals

### ISSUE THREAD

**Issue by RtypeStudios** [tosunthex/CoinGecko#22]
Hi There,

Thanks for the great library, Its has saved me a chunk of code and time. 

I just was wondering what the reason for using doubles is rather than decimals, Things like % changes and so on are fine. But there are monetary values like current price that is financial and would lose accuracy being a double?

for example on the MarketData class:

    [JsonProperty("current_price")]
    public Dictionary<string, double?> CurrentPrice { get; set; }

Thanks!

**Comment by tosunthex** [comment]
Hi @RtypeStudios ,

Thank you for your feedback. That was my mistake. I used a tool for json to c# class conversation and never control it but now i fixed it and added some new things.

**Comment by RtypeStudios** [comment]
Thanks for updating that and thank you for such a fast response!
