### ISSUE TITLE
Depth / CostToMoveUp

### ISSUE THREAD

**Issue by otium99** [tosunthex/CoinGecko#23]
Hi there,

Thank you for this awesome library.

I have a question regarding the Depth information of each exchange you can see at coingecko https://www.coingecko.com/en/coins/bitcoin#markets.

I was wondering where this information is reflected in the library. I found a property in CoinFullDataById.Tickers.CostToMoveUpUsd which might represent this information? However, this property shows 0.

Any ideas where to find this information?

Thank you

**Comment by tosunthex** [comment]
Hi @otium99 

Sorry, I write to little bit late but i check the CoinFullDataById.Tickers.CostToMoveUpUsd and its not zero (0). Could you send me more detail. I need you parameters to try again " Ticker exchange etc. parameters "

**Comment by otium99** [comment]
Hi @tosunthex 

Thank you for your reply.

This is very interesting, that you have values in that property. I have created a small demo project to illustrates the issue.
It also contains a function to go through all the coins on Coingecko, but it seems that none of them return a value. I checked about 200 coins or so.
[CoingeckoOrderBookDepth.zip](https://github.com/tosunthex/CoinGecko/files/6330055/CoingeckoOrderBookDepth.zip)


Here is the screenshot of the output I get:
![image](https://user-images.githubusercontent.com/67344857/115126559-45d66c80-9fa6-11eb-8124-d9ffdafb4e6c.png)

Thank you

**Comment by tosunthex** [comment]
Hi @otium99 

You don't get CostToMoveUpUsd 0 because you use wrong function and you must set depth parameter to "true"

Can you try like this 

`var coinTask = coinGecko.CoinsClient.GetTickerByCoinId(coinId,exchangeIds:new []{"binance"},page:null,includeExchangeLogo:"",order:"",depth:true);`

**Comment by otium99** [comment]
That works. Thank you.
