### ISSUE TITLE
GetMarketChartsByCoinId null issue

### ISSUE THREAD

**Issue by baramustafa** [tosunthex/CoinGecko#24]
Hi,

When I try to call:

client.GetMarketChartsByCoinId("bitcoin", "usd", "max");

It fails with a null error because one of the data points for market_caps is null:

   [
      1491091200000,
      null
    ]

Thanks

**Comment by tosunthex** [comment]
Hi @baramustafa 

I fixed the problem. You can download da lastest nuget package
