### ISSUE TITLE
Use interval instead of intervals in market chart request

### ISSUE THREAD

**Issue by mimirobo** [tosunthex/CoinGecko#27]
In [here](https://github.com/tosunthex/CoinGecko/blob/97ac9e9efe7f1457807f8aa09762b835f9358f11/CoinGecko/Clients/CoinsClient.cs#L146) `intervals` causing wrong response which api accepts `interval`.

**Comment by tosunthex** [comment]
hi @mimirobo 

Thx for reply. I Fixed it
