### ISSUE TITLE
Missing Properties in MarketDataOhlcv (all time high | ath)

### ISSUE THREAD

**Issue by GonzoKK** [tosunthex/CoinGecko#3]
The following ath properties are missing:

ath
ath_change_percentage
ath_date

[JsonProperty("ath")]
public Dictionary<string, double> AllTimeHigh { get; set; }

etc

**Comment by tosunthex** [comment]
Hi @GonzoKK 

I have already these Json properties but I made a wrong class implemantation and fixed it.
