### ISSUE TITLE
IExchangesClient misses GetExchanges(int perPage,string page)

### ISSUE THREAD

**Issue by OxfordGrid** [tosunthex/CoinGecko#31]
The following method from the ExchangesClient class doesn't exist in IExchangesClient:
`public async Task<IReadOnlyList<Exchanges>> GetExchanges(int perPage,string page)`

As a result there is no way to get more than 100 exchanges

**Comment by tosunthex** [comment]
@OxfordGrid 

thanks again. I fixed it you can check the new version
