### ISSUE TITLE
GetAllCoinDataWithId Creates Exception if "genesis_date" is null

### ISSUE THREAD

**Issue by GonzoKK** [tosunthex/CoinGecko#4]
Example is hydro coin

https://api.coingecko.com/api/v3/coins/hydro?localization=false

![image](https://user-images.githubusercontent.com/38913162/53246046-3bff9a00-36b8-11e9-8a00-dd6f5653b456.png)

Quick fix is to Add ItemNullValueHandling to JsonContainerAttribute

[JsonObject(ItemNullValueHandling` = NullValueHandling.Ignore)]

![image](https://user-images.githubusercontent.com/38913162/53246151-8b45ca80-36b8-11e9-8bd4-da8e5b1758b6.png)

Refer https://github.com/JamesNK/Newtonsoft.Json/issues/1429

**Comment by tosunthex** [comment]
Hi @GonzoKK 

NullValueHandling added to genesis_date
