### ISSUE TITLE
Problem with GetCoinMarkets - should be IReadOnlyList?

### ISSUE THREAD

**Issue by GonzoKK** [tosunthex/CoinGecko#5]
I get the exception: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'CoinGecko.Entities.Response.Coins.CoinMarkets' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.

I think it should be public async Task<IReadOnlyList<CoinMarkets>> GetCoinMarkets...

https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=50&page=1&sparkline=false&price_change_percentage=1h%2C24h%2C7d%2C14d%2C30d%2C200d%2C1y

The implications could be wide ranging, for example 

        [JsonProperty("current_price")]
        public Dictionary<string,double> CurrentPrice { get; set; }

should be double (not Dictionary)

etc, etc

**Comment by GonzoKK** [comment]
"current_price" can be double OR Dictionary<string, double>
 
![image](https://user-images.githubusercontent.com/38913162/53639803-ecc6e580-3c32-11e9-81fc-e841a265fccf.png)

Also note null on "roi" and ""total_supply"

**Comment by GonzoKK** [comment]
Thanks @tosunthex I'll test properly tomorrow.

I dont think you're handling "price_change_percentage"

![image](https://user-images.githubusercontent.com/38913162/53667196-f3784b80-3c78-11e9-849e-0a02a71c3c0e.png)

Also I don't see properties for:
"price_change_percentage_1h_in_currency"  
"price_change_percentage_14d_in_currency" 
etc

```
[JsonProperty("price_change_percentage_14d_in_currency", NullValueHandling = NullValueHandling.Ignore)]
public double PriceChangePercentage14dInCurrency { get; set; }
```

ps They all require null handling

**Comment by tosunthex** [comment]
Hi @GonzoKK 

I fixed the problem. Thanks for your fast reply
