### ISSUE TITLE
New nuget package version (1.7.1) 

### ISSUE THREAD

**Issue by cashidze** [tosunthex/CoinGecko#58]
Current nuget package version (version 1.7.0)  doesn't reflect latest merged PR. Can we update/publish nuget package version (1.7.1)?

**Comment by cashidze** [comment]
@tosunthex can you advise how to get it published?

**Comment by tosunthex** [comment]
I will do it but give.me some time @cashidze

**Comment by tosunthex** [comment]
@cashidze updated
