### ISSUE TITLE
Sparkline not working (due to case)

### ISSUE THREAD

**Issue by GonzoKK** [tosunthex/CoinGecko#6]
Seems to be case related...

sparkline=True should be sparkline=true (lowercase)

![image](https://user-images.githubusercontent.com/38913162/53825946-29227a80-3f80-11e9-9589-16b1f78d3c79.png)

Not working example: 
https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&per_page=50&page=1&sparkline=True&price_change_percentage=1h,24h,7d,14d,30d,200d,1y

Working example: 
https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&per_page=50&page=1&sparkline=true&price_change_percentage=1h,24h,7d,14d,30d,200d,1y

**Comment by GonzoKK** [comment]
works if I lowercase sparkline...

![image](https://user-images.githubusercontent.com/38913162/53957695-b03e3280-40e7-11e9-94fa-fbc5c1f403b4.png)

**Comment by tosunthex** [comment]
Hi @GonzoKK fixed
