### ISSUE TITLE
Boolean arguments need be converted to lowercase ie "True" to "true"

### ISSUE THREAD

**Issue by GonzoKK** [tosunthex/CoinGecko#7]
Titlecase does not work...
https://api.coingecko.com/api/v3/simple/price?ids=ethereum-classic&vs_currencies=usd,btc&include_24hr_vol=True&include_last_updated_at=True

lowercase works...
https://api.coingecko.com/api/v3/simple/price?ids=ethereum-classic&vs_currencies=usd,btc&include_24hr_vol=true&include_last_updated_at=true

![image](https://user-images.githubusercontent.com/38913162/55385631-d495ff00-552d-11e9-9b2b-c248cf8df736.png)

**Comment by tosunthex** [comment]
Hi @GonzoKK fixed
