### ISSUE TITLE
GetSimplePrice - 2 Missing arguments: include_market_cap, include_24hr_change

### ISSUE THREAD

**Issue by GonzoKK** [tosunthex/CoinGecko#8]
https://api.coingecko.com/api/v3/simple/price?ids=grin%2Cbeam&vs_currencies=usd%2Cbtc&include_market_cap=true&include_24hr_vol=true&include_24hr_change=true&include_last_updated_at=true

![image](https://user-images.githubusercontent.com/38913162/55387075-0f4d6680-5531-11e9-8fba-00cbe492b10e.png)

**Comment by tosunthex** [comment]
Hi @GonzoKK missing arguments added
