### ISSUE TITLE
New CoinGecko API Parameters

### ISSUE THREAD

**Issue by GonzoKK** [tosunthex/CoinGecko#9]
10 Apr 2019: exchange_ids optional params added for v3/coins/{id}/tickers

10 Apr 2019: coin_ids optional params added for v3/exchanges/{id}/tickers

**Comment by GonzoKK** [comment]
Quick fix - (for reference)

![image](https://user-images.githubusercontent.com/38913162/56026367-46cbc800-5d14-11e9-83c2-c2d4728fa65b.png)

**Comment by tosunthex** [comment]
Hi @GonzoKK fixed
